Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "so-environment"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-sistemas-operativos"
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Aprovisionamiento mediante el script compartido
  config.vm.provision "shell", path: "scripts/setup_env.sh"
end
